---
- additional_code: 'X301'
  measure_type_id: '306'
  content_file: 'excise_code_X301'
  overwrite: false
- additional_code: 'X311'
  measure_type_id: '306'
  content_file: 'excise_code_X311'
  overwrite: false
- additional_code: 'X312'
  measure_type_id: '306'
  content_file: 'excise_code_X312'
  overwrite: false
- additional_code: 'X313'
  measure_type_id: '306'
  content_file: 'excise_code_X313'
  overwrite: false
- additional_code: 'X314'
  measure_type_id: '306'
  content_file: 'excise_code_X314'
  overwrite: false
- additional_code: 'X315'
  measure_type_id: '306'
  content_file: 'excise_code_X315'
  overwrite: false
- additional_code: 'X321'
  measure_type_id: '306'
  content_file: 'excise_code_X321'
  overwrite: false
- additional_code: 'X322'
  measure_type_id: '306'
  content_file: 'excise_code_X322'
  overwrite: false
- additional_code: 'X323'
  measure_type_id: '306'
  content_file: 'excise_code_X323'
  overwrite: false
- additional_code: 'X324'
  measure_type_id: '306'
  content_file: 'excise_code_X324'
  overwrite: false
- additional_code: 'X325'
  measure_type_id: '306'
  content_file: 'excise_code_X325'
  overwrite: false
- additional_code: 'X331'
  measure_type_id: '306'
  content_file: 'excise_code_X331'
  overwrite: false
- additional_code: 'X333'
  measure_type_id: '306'
  content_file: 'excise_code_X333'
  overwrite: false
- additional_code: 'X334'
  measure_type_id: '306'
  content_file: 'excise_code_X334'
  overwrite: false
- additional_code: 'X335'
  measure_type_id: '306'
  content_file: 'excise_code_X335'
  overwrite: false
- additional_code: 'X341'
  measure_type_id: '306'
  content_file: 'excise_code_X341'
  overwrite: false
- additional_code: 'X343'
  measure_type_id: '306'
  content_file: 'excise_code_X343'
  overwrite: false
- additional_code: 'X344'
  measure_type_id: '306'
  content_file: 'excise_code_X344'
  overwrite: false
- additional_code: 'X345'
  measure_type_id: '306'
  content_file: 'excise_code_X345'
  overwrite: false
- additional_code: 'X351'
  measure_type_id: '306'
  content_file: 'excise_code_X351'
  overwrite: false
- additional_code: 'X352'
  measure_type_id: '306'
  content_file: 'excise_code_X352'
  overwrite: false
- additional_code: 'X353'
  measure_type_id: '306'
  content_file: 'excise_code_X353'
  overwrite: false
- additional_code: 'X354'
  measure_type_id: '306'
  content_file: 'excise_code_X354'
  overwrite: false
- additional_code: 'X355'
  measure_type_id: '306'
  content_file: 'excise_code_X355'
  overwrite: false
- additional_code: 'X356'
  measure_type_id: '306'
  content_file: 'excise_code_X356'
  overwrite: false
- additional_code: 'X357'
  measure_type_id: '306'
  content_file: 'excise_code_X357'
  overwrite: false
- additional_code: 'X358'
  measure_type_id: '306'
  content_file: 'excise_code_X358'
  overwrite: false
- additional_code: 'X359'
  measure_type_id: '306'
  content_file: 'excise_code_X359'
  overwrite: false
- additional_code: 'X360'
  measure_type_id: '306'
  content_file: 'excise_code_X360'
  overwrite: false
- additional_code: 'X361'
  measure_type_id: '306'
  content_file: 'excise_code_X361'
  overwrite: false
- additional_code: 'X362'
  measure_type_id: '306'
  content_file: 'excise_code_X362'
  overwrite: false
- additional_code: 'X363'
  measure_type_id: '306'
  content_file: 'excise_code_X363'
  overwrite: false
- additional_code: 'X364'
  measure_type_id: '306'
  content_file: 'excise_code_X364'
  overwrite: false
- additional_code: 'X365'
  measure_type_id: '306'
  content_file: 'excise_code_X365'
  overwrite: false
- additional_code: 'X366'
  measure_type_id: '306'
  content_file: 'excise_code_X366'
  overwrite: false
- additional_code: 'X367'
  measure_type_id: '306'
  content_file: 'excise_code_X367'
  overwrite: false
- additional_code: 'X368'
  measure_type_id: '306'
  content_file: 'excise_code_X368'
  overwrite: false
- additional_code: 'X369'
  measure_type_id: '306'
  content_file: 'excise_code_X369'
  overwrite: false
- additional_code: 'X370'
  measure_type_id: '306'
  content_file: 'excise_code_X370'
  overwrite: false
- additional_code: 'X371'
  measure_type_id: '306'
  content_file: 'excise_code_X371'
  overwrite: false
- additional_code: 'X372'
  measure_type_id: '306'
  content_file: 'excise_code_X372'
  overwrite: false
- additional_code: 'X373'
  measure_type_id: '306'
  content_file: 'excise_code_X373'
  overwrite: false
- additional_code: 'X374'
  measure_type_id: '306'
  content_file: 'excise_code_X374'
  overwrite: false
- additional_code: 'X375'
  measure_type_id: '306'
  content_file: 'excise_code_X375'
  overwrite: false
- additional_code: 'X376'
  measure_type_id: '306'
  content_file: 'excise_code_X376'
  overwrite: false
- additional_code: 'X377'
  measure_type_id: '306'
  content_file: 'excise_code_X377'
  overwrite: false
- additional_code: 'X378'
  measure_type_id: '306'
  content_file: 'excise_code_X378'
  overwrite: false
- additional_code: 'X379'
  measure_type_id: '306'
  content_file: 'excise_code_X379'
  overwrite: false
- additional_code: 'X380'
  measure_type_id: '306'
  content_file: 'excise_code_X380'
  overwrite: false
